### ISSUE TITLE
Can't change Types

### ISSUE THREAD

**Issue by dfeinberg5** [MadimetjaShika/vuetify-google-autocomplete#13]
The `types` prop doesn't seem to work.

The default address works fine, but when you change it to anything else the autocomplete stops working with no errors.

**Comment by MadimetjaShika** [comment]
Hi there, thanks for reporting this. I'll look into it this coming weekend. You're welcome to submit a PR if you need the fix urgently.

**Comment by MadimetjaShika** [comment]
Hi @dfeinberg5. I've published a pre-release ``vuetify-google-autocomplete@2.0.0-alpha.1``. This should resolve the issue you noted. I noticed two problems with this;
* The 'city' and 'region' types weren't working on the example, and this was because of a typo. The SDK expects an array for all the types.
* The prop was not reactive, and therefore the SDK would not get updated with the changed. This is now fixed.

Please check it out and let me know if all's good. This is also updated on the [live example](https://madimetjashika.github.io/vuetify-google-autocomplete/).

In the meantime i'm going to close the issue. Feel free to re-open if the problem still persists.
