### ISSUE TITLE
Refresh the country filter

### ISSUE THREAD

**Issue by iec989** [MadimetjaShika/vuetify-google-autocomplete#14]
I have the country attribute pointing to my model: `:country="form.step1.contact.country.toLowerCase()"`

`form.step1.contact.country.toLowerCase()` change the value based on a dropdown.

Based in the Vue debugger, `form.step1.contact.country.toLowerCase()` value is correct, for instance 'es' - however the filter seems to be working only on load time, no if you modify it afterwards.

Any ideas?

**Comment by MadimetjaShika** [comment]
Hi there, thanks for reporting that. I haven't been able to make updates on this library as yet, but hopefully I can get to all the issues and improvements this coming weekend. You're welcome to submit a PR for the fix if you need the fix urgently.

**Comment by MadimetjaShika** [comment]
Hi @iec989. I've published a pre-release ``vuetify-google-autocomplete@2.0.0-alpha.1``. This should resolve the issue you noted. The problem was that the prop was not being watched for changes and the Google Place SDK was therefore not being updated. Please check it out and let me know if all good.

I'm going to close this issue in the meantime. Feel free to re-open if not resolved.

**Comment by iec989** [comment]
Hi @MadimetjaShika 

It is working as soon as `form.step1.contact.country` got a default value - initially, the value I set is `''`, what throws an error.

If you don't give a default value your `componentRestrictions` es _undefined_ and therfore it will always throw a Javascript error saying that it's not possible to set the country:
![image](https://user-images.githubusercontent.com/11177560/34098538-03b4877a-e3dd-11e7-90a6-b805b00ee208.png)
![image](https://user-images.githubusercontent.com/11177560/34098589-1e0518b0-e3dd-11e7-8b8a-deeff2f6763a.png)

Otherwise it works perfectly fine!

Thank you and good job
