### ISSUE TITLE
Async loading your component and gmaps sdk

### ISSUE THREAD

**Issue by monsdroid** [MadimetjaShika/vuetify-google-autocomplete#15]
Hi, because i do not need your component on the whole application im unable to include google maps in the head.
if you take a look at the vue-gmaps component your can provide a api key  for the component and forget about the script loading.
but if anyone wants to use your component anyway its possible like this

```
components: {
VuetifyGoogleAutocomplete: () => {
        return new Promise((resolve, reject) => {
          if (window.google) {
            resolve(import('vuetify-google-autocomplete'))
          } else {
            let script = document.createElement('script')
            script.onload = () => {
              resolve(import('vuetify-google-autocomplete'))
            }
            script.async = true
            script.src = 'https://maps.googleapis.com/maps/api/js?key=APIKEY&libraries=places'
            document.head.appendChild(script)
          }
        })
      }
```

**Comment by MadimetjaShika** [comment]
Hi @monsdroid, i've published a pre-release ``vuetify-google-autocomplete@2.0.0-alpha.1.``. This should resolve the issue you noted. Please check it out and let me know.

PS: You can now pass the ``api key`` as prop to the component instead of having to import the script in the head of your html, i.e. you can 

```
<vuetify-google-autocomplete :google-api-key="yourGoogleApiKey"></vuetify-google-autocomplete>
```

I'm going to close the issue in the meantime. Feel free to re-open if not resolved.
