### ISSUE TITLE
unexpected token import

### ISSUE THREAD

**Issue by darior87** [MadimetjaShika/vuetify-google-autocomplete#18]
Hi.

When I try to use this cool component into my vue/nuxt project, strange things happen. Here's my error

```
{ /Users/---/node_modules/vuetify-google-autocomplete/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import VuetifyGoogleAutocomplete from './VuetifyGoogleAutocomplete.js'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at r (/Users/---/node_modules/vue-server-renderer/build.js:8147:16)
    at Object.<anonymous> (server-bundle.js:3881:18)
    at __webpack_require__ (webpack:/webpack/bootstrap bae7739f6ed7df19984e:25:0)
    at Object.<anonymous> (plugins/vuetify.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap bae7739f6ed7df19984e:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap bae7739f6ed7df19984e:25:0)
    at Object.<anonymous> (.nuxt/server.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap bae7739f6ed7df19984e:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (/Users/---/node_modules/vue-server-renderer/build.js:8155:21)
    at /Users/---/node_modules/vue-server-renderer/build.js:8213:18 statusCode: 500, name: 'SyntaxError' }

```

My project.json dependencies looks like follows

  ```
"dependencies": {
    "axios": "^0.16.2",
    "body-parser": "^1.17.2",
    "bulma": "^0.5.1",
    "express": "^4.15.3",
    "express-session": "^1.15.3",
    "form-data": "^2.3.1",
    "google-autocomplete-vue": "^1.0.17",
    "nuxt": "^1.3.0",
    "vue": "^2.5.13",
    "vue-i18n": "^7.4.1",
    "vuetify": "^v1.0.0-beta.6",
    "vuetify-cloudinary-upload": "^0.1.1",
    "vuetify-google-autocomplete": "^2.0.0-alpha.1"
  },
```
I tried to use the component globally and related to a page. same error.

tried also a new version of vue (older), but same errors. 

If I try to move from a page to the page in which I imported the component, I can see and use the input autocomplete correctly, but if I refresh that page, it throws that error again.

<img width="1410" alt="schermata 2018-02-07 alle 17 38 50" src="https://user-images.githubusercontent.com/3456533/35928595-ce52c88e-0c2d-11e8-8d46-03763753fe93.png">

**Comment by darior87** [comment]
actually is not related to this component.

in nuxt.config.js add this in the build/extend
```

extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vuetify-google-autocomplete/]
          })
        ]
      }
    }

```

**Comment by MadimetjaShika** [comment]
Hi @darior87, thanks for pointing that out. Happy you managed to solve it. 

So yes, just to add on to your solution (and help someone understand the error in future), that error would typically appear because of two things (as far as I have seen):

1. The consumer can't parse the ``.vue`` file being exported by the library, or

2. The consumer can't parse **ES6**, which the module is written in.

The solution would be to add a ``.vue`` file parser like vue-loader or enable ``.vue`` file parsing for a given loader (if it supports it) as you did, or to add an ES6 to ES5 compiler like [babel](https://babeljs.io), which should compile/transform the library down to ES5 (vanila JS) before it is used (which would change ES6 specific syntax like ``import`` to ``require`` and so forth), making for seamless integration into any JS consuming project.

I am in the process of improving the way the library is written and works (which should also address a number of existing issues already posted), and also exporting the library as ES5 instead, which makes it more flexible for the consumer. 😉
