### ISSUE TITLE
Getting a focus or blur of undefined

### ISSUE THREAD

**Issue by QuentinPotgieter** [MadimetjaShika/vuetify-google-autocomplete#33]
Hi, great package you have made - thank you.

I am receiving: "**_[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'focus' of undefined_**"

    at VueComponent.focus (webpack-internal:///895:293)
    at VueComponent.boundFn [as focus] (webpack-internal:///4:192)
    at VueComponent.mounted (webpack-internal:///474:256)
    at callHook (webpack-internal:///4:2894)
    at Object.insert (webpack-internal:///4:4089)
    at invokeInsertHook (webpack-internal:///4:5863)
    at VueComponent.patch [as __patch__] (webpack-internal:///4:6082)
    at VueComponent.Vue._update (webpack-internal:///4:2646)
    at VueComponent.updateComponent (webpack-internal:///4:2764)
    at Watcher.get (webpack-internal:///4:3114)

The first which take me to:
```
    /**
     * Focus the input
     */
    focus: function focus() {
      this.$refs.autocomplete.focus();
    },
```
The package is working great on a single usage, but it still throws out this error. When I have it in a v-for loop in order to edit the addresses, then the input does not work at all and I suspect it has got to do with the mount:

    mounted: function () {
      this.$refs.address.focus();
    },

Is there any workaround not to use refs?
Thank you in advance.

**Comment by MadimetjaShika** [comment]
Hi @QuentinPotgieter 

Just to make sure I understand you correctly, are you saying when you include the component multiple times on the same "view", you get that error? If so, I am unable to reproduce that error. Could you please provide a code sample of your scenario which triggers that error, or perhaps correct my understanding if I misunderstood.

Just as a side note, the ``focus()`` method you refere to actually does not get used at all in the component. Instead, the ``onFocus()`` method is the one that gets called on the ``v-text-field``'s ``focus`` event. Unfortunately there's a bunch of methods and props which have become irrelevant and obsolete since ``v2.0.0.*``, which I need to clean-up.

**Comment by QuentinPotgieter** [comment]
Hi @MadimetjaShika,

Thank you for your response. I am still receiving the same issue but believe it to be coming from somewhere in my vuejs stack. Kindly close this ticket.

Thank you for your assistance.

**Comment by MadimetjaShika** [comment]
Thanks @QuentinPotgieter. Feel free to open a new issue if you are still experiencing issues with this or need help.

**Comment by stavro-gh** [comment]
i had the same problem using the component in an cli3 project.
this.$refs.address.focus() did not work for me but **this.$refs.address.$refs.textField.focus()**; works.
