### ISSUE TITLE
[Bug] - When using the "clearable" option placechanged isn't triggered

### ISSUE THREAD

**Issue by gabaum10** [MadimetjaShika/vuetify-google-autocomplete#37]
When using the vuetify `clearable` option, when you click the clear button it clears out the value, but the placechanged callback isn't fired.  

On top of that, the inputChange event never seems to fire.  I was going to try to hack around that and see if it'll give me something to listen to an evaluate for nothing.  But alas, that doesn't work either.

**Comment by gabaum10** [comment]
I actually tried to dig into this to see if I could figure out what's going on and holy crap I'm confused.  Why are you trying to do so much with events?  Why not just bind the v-model on the text input and setup a watcher on that property.  Then you don't need to try to wire up all the events and it'd be more reliable.

**Comment by gabaum10** [comment]
Hmm... this is working now.  Wonder what I was doing wrong before.  I wonder if it was another side effect of google being loaded multiple times.  Anyway..

**Comment by gabaum10** [comment]
Oh no it is still now working.  Right.

**Comment by gabaum10** [comment]
I see why it's not using a model now.  We don't want it to actually trigger the change unless the user actually selects a location.  I think.  How to make the clear work though?  I'm not sure.

**Comment by gabaum10** [comment]
I submitted a PR #39

**Comment by MadimetjaShika** [comment]
Hi @gabaum10

Thanks for the PR. It's been merged and published under version ``2.0.0-Alpha.9``.

To answer your previous question, yes the scenario you mentioned is one of the reasons why we are not directly binding via the v-model for reactivity, and why events are explicitly emitted instead.

It's  worth noting as well, part of the reason why I began the version ``2.*`` journey is because I found that the design of the initial codebase from the original fork was somewhat limiting for some of the scenarios of this library, although it worked/works great for the fork. A read through the past release notes might help you understand the changes which were made and why they were made. I still consider the design of this library in a WIP state at the moment, so feel free to suggest design alternatives.
