### ISSUE TITLE
value not updating when place changes

### ISSUE THREAD

**Issue by DoritoBandito** [MadimetjaShika/vuetify-google-autocomplete#42]
`_this2.autocompleteText = document.getElementById(_this2.id).value;`

`value` in this code is not updated upon getting a new place. Not sure my implementation is correct or not but when selecting an option the text does not update in the input.

**Comment by MadimetjaShika** [comment]
Hi, thanks for pointing this out. I found this bug rather odd because this is something that has been working alright all along. I imagine it possibly could have slipped through the cracks through another fix. I've published version ``2.0.0-Beta.1`` with the fix. Thanks again. Let me know if there are still issues please.
