### ISSUE TITLE
Vue CLI 3 SPA need to reload site

### ISSUE THREAD

**Issue by szymon-krysztofiak-dev** [MadimetjaShika/vuetify-google-autocomplete#56]
I need to reload my SPA site every single time when i change my route. I checked the library. When I remove `destroyed: function destroyed() {
window.vgaMapState.initMap = false
},` everything works fine.

@MadimetjaShika can you explain this piece of code?

Regards,
Szymon

**Comment by albertvolkman** [comment]
Yes, I'm having the same issue. Removing that line of code fixes it.

**Comment by szymon-krysztofiak-dev** [comment]
Instead of removing the code from the library, I just added this fragment to my component with `true` flag. Like this: `destroyed() { window.vgaMapState.initMap = true }`
Works well, but it is unreadable to others in the project...

**Comment by MadimetjaShika** [comment]
Hi Guys,

Thanks for posting this issue. This should be resolved in the next release, which I will publish within an hour or two. ``v2.0.0-beta.5``

@SzymonKrysztofiak the reason behind the ``destroyed: function destroyed() { window.vgaMapState.initMap = false }`` was to ensure that we "reset" the maps init indicator, so that the component forces a reload of the places library when the component is reloaded, be it through a vue-router page navigation or any other form of page navigation.

This worked fine, however the problem was that on mounted, the "window.maps" object was not always set, which caused the places library to not be re-loaded as expected. That check is not completely necessary, so I have removed it.
