### ISSUE TITLE
multiple types

### ISSUE THREAD

**Issue by VincentMRA** [MadimetjaShika/vuetify-google-autocomplete#57]
I would like to add multiple types. (address, establishments and (regions))
I believe it works when i submit an array, but it also returns an error.

Could you please fix this? :)

Cheers,

**Comment by SzymonKrysztofiak** [comment]
Where You want to add multiple types? In searchbar?

**Comment by MadimetjaShika** [comment]
Hi @VincentMRA,

Thanks for the issue. However according to the Google Places Autocomplete docs: 

> In general only a single type is allowed.

There is an exception however where you can pass "geocode" and "establishment", however according to the docs, ``this will have the same effect as specifying no types``. Hence only one type is catered for on this library.

Please refer [here](https://developers.google.com/places/supported_types#table3).

The error you saw was likely because the ``types`` prop expects a string and not an array, inline with what I mentioned above.

Closing this issue for now. Please do feel free to re-open and let me know if you have come across other documentation that suggests multiple types may safely be passed to this parameter, and i'll be happy to make the change.
