### ISSUE TITLE
':append-icon-cb' is deprecated

### ISSUE THREAD

**Issue by pitapaya** [MadimetjaShika/vuetify-google-autocomplete#71]
Warning message I get when using 'append-icon-cb' prop: [Vuetify] ':append-icon-cb' is deprecated, use '@click:append' instead.

Here's my package.json
`"dependencies": {
  "vuetify": "^1.5.13",
  "vuetify-google-autocomplete": "^2.0.0-beta.6"
}`

I change to use '@click:append', I get a different error:
'DOMException: Failed to execute 'setAttribute' on 'Element': '@click:append' is not a valid attribute name.'

Thanks
PL

**Comment by MadimetjaShika** [comment]
Hi there. This is probably because the ``append-icon-cb`` prop got disabled in a more recent release to the one which ``2.0.0-beta.6`` of this library was dependant on.

I am planning to enable full support for Vuetify 2 during December, once that's done you shoulnd't be seeing this warning any longer.

**Comment by MadimetjaShika** [comment]
Hi, ``append-icon-cb`` has been removed in ``v2.0.0``, along with all other ``v1.*a`` props.

Feel free to re-open if you still experience problems.
