### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mhsystem** [MadimetjaShika/vuetify-google-autocomplete#8]
Hello, do you have any idea, why it is not work under webpackbin.com? or can you create example?
I have error:
Error: Module parse failed: /root/webpack-packager/packages/2790353294/node_modules/vuetify-google-autocomplete/src/VuetifyGoogleAutocomplete.vue Unexpected token (1:0) You may need an appropriate loader to handle this file type. | <template> | <v-text-field | hide-details

**Comment by MadimetjaShika** [comment]
Hi there. Hmm, this is a slightly odd issue. I've tried to create a quick webpackbin project and I seem to be getting the same result. Not exactly sure what the problem might be, will try looking slightly deeper into this and let you know.

**Comment by dmoganty** [comment]
seems it will give only address

**Comment by MadimetjaShika** [comment]
Hi there,

This problem should now be resolved in [the latest v2.0.0-alpha.4 release](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases) . This was due to the project being exported as a .vue file, which meant that you needed to have an appropriate loader for that file type. The project is now exported as a ``.js`` file and ES5 format.

This should allow for usage within plain HTML/JS projects, and also within webpackbin without needing any fancy loaders.

Please do re-open this issue if you still experience this problem.

Thanks!
